/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jmat.deteksisenyawa.internalframe.senyawa;

import com.uiMIF.JTextEx;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.JTextPane;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import jmat.deteksisenyawa.controller.ControllerSenyawa;
import jmat.deteksisenyawa.entity.EntitySenyawa;
import jmat.deteksisenyawa.frame.DeteksiSenyawa;
import jmat.deteksisenyawa.internalframe.rule.InternalRule;
import jmat.deteksisenyawa.listener.ListenerSenyawa;
import jmat.deteksisenyawa.model.ModelSenyawa;

/**
 *
 * @author hasani
 */
public class InternalSenyawa extends javax.swing.JInternalFrame
        implements ListenerSenyawa {

    /**
     * Creates new form InternalSenyawa
     */
    private DeteksiSenyawa deteksiSenyawa;
    private ModelSenyawa modelSenyawa;
    private ControllerSenyawa controllerSenyawa;
    private String oldNamaSenyawa;
    private String oldRumusEmpiris;
    private String oldRumusMolekul;

    public InternalSenyawa() {
        initComponents();
        connectDatabase();
    }

    public JTextEx getTxtIdSenyawa() {
        return txtIdSenyawa;
    }

    public JTextPane getTxtRMolekul() {
        return txtRMolekul;
    }

    public JTextPane getTxtRempiris() {
        return txtRempiris;
    }

    public JTextEx getTxtnamaZat() {
        return txtnamaZat;
    }

    public JProgressBar getProgresbarSenyawa() {
        return progresbarSenyawa;
    }

    public JLabel getLblKeterangan() {
        return lblKeterangan;
    }

    public DeteksiSenyawa getDeteksiSenyawa() {
        return deteksiSenyawa;
    }

    public void setDeteksiSenyawa(DeteksiSenyawa deteksiSenyawa) {
        this.deteksiSenyawa = deteksiSenyawa;
    }

    public JButton getBtnClear() {
        return btnClear;
    }

    public JButton getBtnSimpan() {
        return btnSimpan;
    }

    public JButton getBtnNormalRE() {
        return btnNormalRE;
    }

    public JButton getBtnNormalRM() {
        return btnNormalRM;
    }

    public JButton getBtnSubRE() {
        return btnSubRE;
    }

    public JButton getBtnSubRM() {
        return btnSubRM;
    }

    public JButton getBtnSupRE() {
        return btnSupRE;
    }

    public JButton getBtnSupRM() {
        return btnSupRM;
    }

    public void setTitleBaru(String title) {
        lblKeterangan.setVisible(false);
        this.setTitle(title);
    }

    private void connectDatabase() {
        modelSenyawa = new ModelSenyawa();
        controllerSenyawa = new ControllerSenyawa();
        controllerSenyawa.setModelSenyawa(modelSenyawa);
        modelSenyawa.setListenerSenyawa(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdSenyawa = new com.uiMIF.JTextEx();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnamaZat = new com.uiMIF.JTextEx();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRempiris = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRMolekul = new javax.swing.JTextPane();
        btnSimpan = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnSubRE = new javax.swing.JButton();
        btnSupRE = new javax.swing.JButton();
        btnNormalRE = new javax.swing.JButton();
        btnNormalRM = new javax.swing.JButton();
        btnSupRM = new javax.swing.JButton();
        btnSubRM = new javax.swing.JButton();
        progresbarSenyawa = new javax.swing.JProgressBar();
        lblKeterangan = new javax.swing.JLabel();

        txtIdSenyawa.setEditable(false);
        txtIdSenyawa.setInputType(com.uiMIF.JTextEx.TypeText.Number);

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nama Zat");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Rumus Empiris");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Rumus Molekul");

        txtnamaZat.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        txtnamaZat.setMaxlength(550);

        txtRempiris.setContentType("text/html"); // NOI18N
        txtRempiris.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jScrollPane1.setViewportView(txtRempiris);

        txtRMolekul.setContentType("text/html"); // NOI18N
        txtRMolekul.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jScrollPane2.setViewportView(txtRMolekul);

        btnSimpan.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnSubRE.setText("<html>X<sub>2</sub></html>");
        btnSubRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubREActionPerformed(evt);
            }
        });

        btnSupRE.setText("<html>X<sup>2</sup></html>");
        btnSupRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupREActionPerformed(evt);
            }
        });

        btnNormalRE.setText("Normal Text");
        btnNormalRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNormalREActionPerformed(evt);
            }
        });

        btnNormalRM.setText("Normal Text");
        btnNormalRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNormalRMActionPerformed(evt);
            }
        });

        btnSupRM.setText("<html>X<sup>2</sup></html>");
        btnSupRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupRMActionPerformed(evt);
            }
        });

        btnSubRM.setText("<html>X<sub>2</sub></html>");
        btnSubRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubRMActionPerformed(evt);
            }
        });

        lblKeterangan.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        lblKeterangan.setForeground(new java.awt.Color(66, 208, 75));
        lblKeterangan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblKeterangan.setText("Sukses Menyimpan data");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnamaZat, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnSubRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSupRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnNormalRE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnSubRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSupRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnNormalRM))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblKeterangan)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnSimpan)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnClear))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                                        .addComponent(progresbarSenyawa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, txtnamaZat});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnClear, btnSimpan});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnamaZat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSupRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNormalRE))
                    .addComponent(btnSubRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(11, 11, 11)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSupRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNormalRM))
                    .addComponent(btnSubRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progresbarSenyawa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKeterangan)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSubRE, btnSupRE});

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:

        deteksiSenyawa.internalSenyawa = null;
        deteksiSenyawa = null;


    }//GEN-LAST:event_formInternalFrameClosed
    public void setSenyawaObjekOld(String nm, String re, String rm) {
        this.oldNamaSenyawa = nm;
        this.oldRumusEmpiris = re;
        this.oldRumusMolekul = rm;
    }

    private Boolean validasiPerubahan() {
        Boolean cek = false;

        if (!txtnamaZat.getText().equals(oldNamaSenyawa)
                || !txtRempiris.getText().equals(oldRumusEmpiris)
                || !txtRMolekul.getText().equals(oldRumusMolekul)) {
            cek = true;
        }

        return cek;
    }

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        switch (getTitle()) {
            case "Tambah Zat":
                controllerSenyawa.insertSenyawa(this);
                break;
            case "Ubah Zat":
                if (validasiPerubahan() == true) {
                    controllerSenyawa.updateSenyawa(this);
                } else {
                    btnClearActionPerformed(evt);
                    dispose();
                }
                break;
            default:
                break;
        }

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtnamaZat.setText("");
        txtRempiris.setText("");
        txtRMolekul.setText("");

    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSubREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubREActionPerformed
        // TODO add your handling code here:
        String selectedText = txtRempiris.getSelectedText();
        Style style = txtRempiris.addStyle(null, null);
        StyleConstants.setSubscript(style, true);
        if (selectedText != null) {
            txtRempiris.getStyledDocument().setCharacterAttributes(txtRempiris.getSelectionStart(), selectedText.length(), style, false);

        } else {
            JOptionPane.showMessageDialog(this, "Seleksi huruf pada rumus empiris !! ", "WARRNING", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSubREActionPerformed

    private void btnSupREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupREActionPerformed
        // TODO add your handling code here:
        String selectedText = txtRempiris.getSelectedText();
        Style style = txtRempiris.addStyle(null, null);
        StyleConstants.setSuperscript(style, true);
        if (selectedText != null) {
            txtRempiris.getStyledDocument().setCharacterAttributes(txtRempiris.getSelectionStart(), selectedText.length(), style, false);

        } else {
            JOptionPane.showMessageDialog(this, "Seleksi huruf pada rumus empiris !! ", "WARRNING", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSupREActionPerformed

    private void btnNormalREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNormalREActionPerformed
        // TODO add your handling code here:
        String selectedText = txtRempiris.getSelectedText();
        Style style = txtRempiris.addStyle(null, null);
        StyleConstants.setSuperscript(style, false);
        StyleConstants.setSubscript(style, false);
        if (selectedText != null) {
            txtRempiris.getStyledDocument().setCharacterAttributes(txtRempiris.getSelectionStart(), selectedText.length(), style, false);

        } else {

            txtRempiris.selectAll();
            String normalText = txtRempiris.getSelectedText();
            if (normalText instanceof String) {
                txtRempiris.getStyledDocument().setCharacterAttributes(txtRempiris.getSelectionStart(), normalText.length(), style, false);
                txtRempiris.setSelectionEnd(0);
            }

        }
    }//GEN-LAST:event_btnNormalREActionPerformed

    private void btnNormalRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNormalRMActionPerformed
        // TODO add your handling code here:
        String selectedText = txtRMolekul.getSelectedText();
        Style style = txtRMolekul.addStyle(null, null);
        StyleConstants.setSuperscript(style, false);
        StyleConstants.setSubscript(style, false);
        if (selectedText != null) {
            txtRMolekul.getStyledDocument().setCharacterAttributes(txtRMolekul.getSelectionStart(), selectedText.length(), style, false);

        } else {
            txtRMolekul.selectAll();
            String normalText = txtRMolekul.getSelectedText();
            if (normalText instanceof String) {
                txtRMolekul.getStyledDocument().setCharacterAttributes(txtRMolekul.getSelectionStart(), normalText.length(), style, false);
                txtRMolekul.setSelectionEnd(0);
            }
        }
    }//GEN-LAST:event_btnNormalRMActionPerformed

    private void btnSupRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupRMActionPerformed
        // TODO add your handling code here:
        String selectedText = txtRMolekul.getSelectedText();
        Style style = txtRMolekul.addStyle(null, null);
        StyleConstants.setSuperscript(style, true);
        if (selectedText != null) {
            txtRMolekul.getStyledDocument().setCharacterAttributes(txtRMolekul.getSelectionStart(), selectedText.length(), style, false);

        } else {
            JOptionPane.showMessageDialog(this, "Seleksi huruf pada rumus molekul !! ", "WARRNING", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSupRMActionPerformed

    private void btnSubRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubRMActionPerformed
        // TODO add your handling code here:
        String selectedText = txtRMolekul.getSelectedText();
        Style style = txtRMolekul.addStyle(null, null);
        StyleConstants.setSubscript(style, true);
        if (selectedText != null) {
            txtRMolekul.getStyledDocument().setCharacterAttributes(txtRMolekul.getSelectionStart(), selectedText.length(), style, false);

        } else {
            JOptionPane.showMessageDialog(this, "Seleksi huruf pada rumus molekul !! ", "WARRNING", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSubRMActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnNormalRE;
    private javax.swing.JButton btnNormalRM;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnSubRE;
    private javax.swing.JButton btnSubRM;
    private javax.swing.JButton btnSupRE;
    private javax.swing.JButton btnSupRM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblKeterangan;
    private javax.swing.JProgressBar progresbarSenyawa;
    private com.uiMIF.JTextEx txtIdSenyawa;
    private javax.swing.JTextPane txtRMolekul;
    private javax.swing.JTextPane txtRempiris;
    private com.uiMIF.JTextEx txtnamaZat;
    // End of variables declaration//GEN-END:variables

    @Override
    public void OnInsert(EntitySenyawa entitySenyawa) {
        if (deteksiSenyawa.internalTBSenyawa instanceof InternalTBSenyawa) {
            InternalTBSenyawa internalTBSenyawa;
            internalTBSenyawa = (InternalTBSenyawa) deteksiSenyawa.internalTBSenyawa;
            internalTBSenyawa.getTabelModelSenyawa().add(entitySenyawa);
        }
        if (deteksiSenyawa.internalRule instanceof InternalRule) {
            InternalRule internalRule;
            internalRule = (InternalRule) deteksiSenyawa.internalRule;
            internalRule.getComboBoxModelSenyawa().addElement(entitySenyawa);

        }
    }

    @Override
    public void OnUpdate(EntitySenyawa entitySenyawa) {
        if (deteksiSenyawa.internalTBSenyawa instanceof InternalTBSenyawa) {
            InternalTBSenyawa internalTBSenyawa;
            internalTBSenyawa = (InternalTBSenyawa) deteksiSenyawa.internalTBSenyawa;
            int selectedRow = internalTBSenyawa.getTabelSenyawa().getSelectedRow();
            internalTBSenyawa.getTabelModelSenyawa().set(selectedRow, entitySenyawa);
            dispose();
        } else if (deteksiSenyawa.internalRule instanceof InternalRule) {
            InternalRule internalRule;
            internalRule = (InternalRule) deteksiSenyawa.internalRule;
            if (internalRule.getComboBoxModelSenyawa().getSelectedItem() instanceof EntitySenyawa) {
                EntitySenyawa entitySenyawaObjekLama;
                entitySenyawaObjekLama = (EntitySenyawa) internalRule.getComboBoxModelSenyawa().getSelectedItem();
                if (entitySenyawaObjekLama.getIdSenyawa().toString()
                        .equals(entitySenyawa.getIdSenyawa().toString())) {
                    int selectedIndex = internalRule.getComboSenyawa().getSelectedIndex();

                    if (entitySenyawa.getIdSenyawa().toString()
                            .equals(internalRule.getComboBoxModelSenyawa().getElementAt(selectedIndex).getIdSenyawa().toString())) {
                        internalRule.getComboBoxModelSenyawa().removeElementAt(selectedIndex);
                        internalRule.getComboBoxModelSenyawa().insertElementAt(entitySenyawa, selectedIndex);
                        internalRule.getComboSenyawa().setSelectedIndex(selectedIndex);

                    }

                } else {
                    int size = internalRule.getComboBoxModelSenyawa().getSize();
                    for (int index = 0; index < size; index++) {
                        if (entitySenyawa.getIdSenyawa().toString()
                                .equals(internalRule.getComboBoxModelSenyawa().getElementAt(index).getIdSenyawa().toString())) {
                            internalRule.getComboBoxModelSenyawa().removeElementAt(index);
                            internalRule.getComboBoxModelSenyawa().insertElementAt(entitySenyawa, index);
                        }
                    }
                }
            }
            dispose();
        } else {
            dispose();
        }




    }
}
